# Generated by Django 4.1.7 on 2023-02-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
    ]
