# Generated by Django 4.1.7 on 2023-02-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('courses', '0003_remove_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_course', to='groups.group'),
        ),
    ]
