# Generated by Django 4.1.6 on 2023-02-02 21:50

import datetime
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='Group', max_length=80, verbose_name='Group name')),
                ('groups_start_data', models.DateField(default=datetime.date.today, validators=[groups.validators.validate_start_date])),
                ('group_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
