# Generated by Django 4.1.7 on 2023-02-23 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('group_description', models.CharField(max_length=150)),
                ('start_date', models.DateField(default=datetime.date.today, validators=[groups.validators.validate_start_date])),
                ('end_date', models.DateField(blank=True, null=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='courses.course')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
