# Generated by Django 4.1.7 on 2023-02-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_first_name_alter_student_last_name'),
        ('teachers', '0002_alter_teacher_birthday_alter_teacher_email_and_more'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_group', to='students.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='groups', to='teachers.teacher'),
        ),
    ]
