# Generated by Django 4.1.7 on 2023-02-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
