# Generated by Django 4.1.5 on 2023-01-20 17:16

import datetime
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groups_start_data',
            field=models.DateField(default=datetime.date.today, validators=[groups.validators.validate_start_date]),
        ),
    ]
